// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models
{
    public partial class user
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string passwordHash { get; set; }
    }
}